apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./k8s/*
build:
  local:
    push: false
  artifacts:
    - image: kazuku/kazuku-admin-api
      context: admin-api  # the folder to look in for the Dockerfile and the sync below
      docker:
        dockerfile: Dockerfile
        noCache: true
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
          - src: 'src/**/*.json'
            dest: .

