# whenever docker build gets run, it tries to cache as much as possible, line-by-line. If it has to run a line, it will always run
#  every line after that line
FROM node:16-alpine
# sets the root folder that all subsequent commands will execute inside of
WORKDIR "/app"
# this causes npm install to only run if package.json is changed. If package.json did not change, docker will know it has these steps
#  cached and does not need to run them again
COPY ./package.json ./
RUN npm install
# all the other files (everything else) needs to be copied - only run if something other than package.json changed
COPY . .
# runs "npm run dev" in the container once it's ready
CMD ["npm", "run", "dev"]
