title: Site
type: object
required:
  - orgId
  - code
  - name
properties:
  id:
    type: string
    example: 63e55fb10b301acaf0e3017d
  orgId:
    type: string
    example: 5aad6ee15069c6aa32dea338
  code:
    type: string
    example: test-site-one
  name:
    type: string
    example: Test Site One
  domainName:
    type: string
    example: testsiteone.com
  description:
    type: string
    example: It's a test site
  created:
    type: string
    format: date
    example: 2021-02-15T17:45:25.464Z
  createdBy:
    type: string
    example: joe@acme.com
  updated:
    type: string
    format: date
    example: 2022-02-15T17:45:25.464Z
  updatedBy:
    type: string
    example: joe@acme.com
