openapi: 3.0.0
info:
  title: Kazuku API
  description: API for Kazuku admin interface
  version: 1.0.0

servers:
  - url: http://{host}:{port}
    description: local server
    variables:
      host:
        default: localhost
        description: api running locally
      port:
        default: 3001

components:
  schemas:
    $ref: './schemas/index.yml'
  responses:
    $ref: './responses/index.yml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

#global security, applied to the whole API. If you need to apply it to just a few operations, add security on the operation level instead
#paths:
#  /something:
#    get:
#      security:
#        - bearerAuth: []
security:
  - bearerAuth: []

paths:
  $ref: './paths/index.yml'

