name: admin-api-test

on:
  pull_request:
    paths:
      - 'admin-api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    env:
      KAZUKU_ENV: ${{ vars.KAZUKU_ENV }}
      DEVICEID_MAX_AGE_DAYS: ${{ vars.DEVICEID_MAX_AGE_DAYS }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      - name: Output Environment Variables
        run: |
          echo "KAZUKU_ENV: $KAZUKU_ENV"
      - uses: actions/checkout@v4
      - run: cd admin-api && npm install && npm run test:ci
