name: admin-api-tests

on:
  pull_request:
    paths:
      - 'admin-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd admin-api && npm install && npm run test:ci
