name: admin-api-deploy

on:
  push:
    branches:
      - master
    paths:
      - 'admin-api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Build docker image
        run: cd admin-api && docker build -t kazuku/kazuku-admin-api .
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Push docker image to Docker Hub
        run: docker push kazuku/kazuku-admin-api
      - name: Deploy to GCP
        run: echo "Deploying to DEV in GCP..."
#      - name: Rollout deployment on GCP
#        run: kubectl rollout restart deployment admin-api-deployment # check the naming here

